runMode: debug               # 开发模式, debug, release, test
addr: :8080                  # HTTP绑定端口
name: demo              # API Server的名字

mysql:
  username: test
  password: 123456
  name: test
  addr: localhost

db:
  LogMode: true