basePath: /v2
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a  server Petstore server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger API
  version: "1.0"
paths:
  /user:
    post:
      consumes:
      - application/json
      description: path for debug
      produces:
      - application/json
      summary: Add new user to the database
      tags:
      - debug
swagger: "2.0"
